### ISSUE TITLE
[1.15.2] New update to refinedstorage requires all addons mods to update

### ISSUE THREAD

**Issue by IchigoGames** [JavaPowerFR/StorageTech#3]
i reported this crash to refinedstorage and was told it was due to a addon mod and that all addons would need to update to work with current version of refined storage so i removed the first addon i knew i had this mod and it stopped crashing.

Minecraft 1.15.2
forge 31.2.21
refinedstorage-1.8.5
StorageTech R7.1

crash report https://pastebin.com/wfTLa7CC

**Comment by IchigoGames** [comment]
https://github.com/refinedmods/refinedstorage/issues/2580

**Comment by JavaPowerFR** [comment]
We have fixed this issue in the new version R7.2.
Refined Storage old api 1.8.3+27 -> new api 1.8.6+55
