### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by hodo1962** [JavaPowerFR/StorageTech#5]
Right click on the Structor Constructor freezes and then crashes the game.

Minecraft: 1.16.3
Forge: 34.1.42
Refined Storage: 1.9.8

Crash Report: 
[crash-2020-11-23_15.18.49-server.txt](https://github.com/JavaPowerFR/StorageTech/files/5583594/crash-2020-11-23_15.18.49-server.txt)

**Comment by JavaPowerFR** [comment]
Hi, we have been fixed the issue in the [1.16.3-R1.3](https://www.curseforge.com/minecraft/mc-mods/storage-tech/files/3120807)

Thanks you !
