### ISSUE TITLE
Parts combining issues

### ISSUE THREAD

**Issue by ASUT0R0** [JavaPowerFR/StorageTech#6]
1, Combining chemical storage parts makes custom storage part instead of custom chemical storage part.
2, Some combination of energy/fluid storage parts do the same thing(should happen at least with the same capacity custom parts).
3, Combining large capacity energy storage parts makes 1/10 capacityof expected(e.g. 25.6M + 102.4M = 128K, not 128M).

Forge:35.1.4
Refined Storage:1.9.9
Mekanism:1.16.4-10.0.17.444
Storage Tech:1.16.4-R1.0

**Comment by JavaPowerFR** [comment]
I have fixed all issues in the new version. I can't publied the new version for this moment, i don't have access to my curseforge project but here is a temporary link https://drive.google.com/drive/folders/1HeGLzDuPxXtwfjhiUaj0mTuvSKmu4RWc?usp=sharing.

Thank you for your feedback.
