### ISSUE TITLE
Crash on Mixin config 1.16.4

### ISSUE THREAD

**Issue by 3x1at1on** [JavaPowerFR/StorageTech#7]
Game crashes while reading/creating mixin config.

Minecraft 1.16.4
Forge 35.1.12 and also Forge 35.1.13
Storagetech 1.16.4 R1.1

Log https://pastebin.com/tsUTLUXP
Detailed debug log https://pastebin.com/vcTBfUDh

**Comment by JavaPowerFR** [comment]
Hi, Is fixed now in 1.16.4-R1.2
thank for reporting the issue.
